<?php

namespace App\Policies;

class RegrasEnum
{
    const USUARIO_DELETAR = "USUARIO_DELETAR";
    const USUARIO_VISUALIZAR = "USUARIO_VISUALIZAR";
    const USUARIO_CRIAR = "USUARIO_CRIAR";
    const USUARIO_ATUALIZAR = "USUARIO_ATUALIZAR";

    const PERFIL_DELETAR = "PERFIL_DELETAR";
    const PERFIL_VISUALIZAR = "PERFIL_VISUALIZAR";
    const PERFIL_CRIAR = "PERFIL_CRIAR";
    const PERFIL_ATUALIZAR = "PERFIL_ATUALIZAR";

    const REGRA_DELETAR = "REGRA_DELETAR";
    const REGRA_VISUALIZAR = "REGRA_VISUALIZAR";
    const REGRA_CRIAR = "REGRA_CRIAR";
    const REGRA_ATUALIZAR = "REGRA_ATUALIZAR";

    const ALUNO_DELETAR = "ALUNO_DELETAR";
    const ALUNO_VISUALIZAR = "ALUNO_VISUALIZAR";
    const ALUNO_CRIAR = "ALUNO_CRIAR";
    const ALUNO_ATUALIZAR = "ALUNO_ATUALIZAR";

    const PRESENCA_DELETAR = "PRESENCA_DELETAR";
    const PRESENCA_VISUALIZAR = "PRESENCA_VISUALIZAR";
    const PRESENCA_CRIAR = "PRESENCA_CRIAR";
    const PRESENCA_ATUALIZAR = "PRESENCA_ATUALIZAR";

    const COMENTARIO_DELETAR = "COMENTARIO_DELETAR";
    const COMENTARIO_VISUALIZAR = "COMENTARIO_VISUALIZAR";
    const COMENTARIO_CRIAR = "COMENTARIO_CRIAR";
    const COMENTARIO_ATUALIZAR = "COMENTARIO_ATUALIZAR";

    const NOTA_DELETAR = "NOTA_DELETAR";
    const NOTA_VISUALIZAR = "NOTA_VISUALIZAR";
    const NOTA_CRIAR = "NOTA_CRIAR";
    const NOTA_ATUALIZAR = "NOTA_ATUALIZAR";

    const DISCIPLINA_DELETAR = "DISCIPLINA_DELETAR";
    const DISCIPLINA_VISUALIZAR = "DISCIPLINA_VISUALIZAR";
    const DISCIPLINA_CRIAR = "DISCIPLINA_CRIAR";
    const DISCIPLINA_ATUALIZAR = "DISCIPLINA_ATUALIZAR";

    const TURMA_DELETAR = "TURMA_DELETAR";
    const TURMA_VISUALIZAR = "TURMA_VISUALIZAR";
    const TURMA_CRIAR = "TURMA_CRIAR";
    const TURMA_ATUALIZAR = "TURMA_ATUALIZAR";

    const ESCOLA_DELETAR = "ESCOLA_DELETAR";
    const ESCOLA_VISUALIZAR = "ESCOLA_VISUALIZAR";
    const ESCOLA_CRIAR = "ESCOLA_CRIAR";
    const ESCOLA_ATUALIZAR = "ESCOLA_ATUALIZAR";
}
